# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
from pathlib import Path

import pytest
from _pytest.mark.expression import Expression
from testing_utils import BazelTools


_DEFAULT_RUST_TARGET = "//feature_integration_tests/test_scenarios/rust:rust_test_scenarios"
_LIFECYCLE_ONLY_RUST_TARGET = "//feature_integration_tests/test_scenarios/rust:rust_lifecycle_test_scenarios"
_LIFECYCLE_TESTS_DIR = Path("feature_integration_tests/test_cases/tests/lifecycle")


def _selected_versions(session: pytest.Session) -> set[str]:
    """Return the scenario variants explicitly requested by the mark expression.

    Uses pytest's own marker expression evaluator so that logical operators and
    negations are respected. For example, ``-m "not rust"`` must *not* select the
    Rust build, while a plain substring check would incorrectly match it.
    Falls back to all variants when no expression is given or parsing fails.
    """
    mark_expression = session.config.option.markexpr or ""
    if not mark_expression:
        return {"rust", "cpp"}
    try:
        expr = Expression.compile(mark_expression)
    except Exception:  # noqa: BLE001 – malformed expression; fall back to all variants
        return {"rust", "cpp"}
    selected_versions = {version for version in ("rust", "cpp") if expr.evaluate(lambda name: name == version)}
    return selected_versions or {"rust", "cpp"}


def _is_lifecycle_only_selection(session: pytest.Session) -> bool:
    """Return True when pytest was invoked only for lifecycle test paths."""
    if not session.config.args:
        return False

    normalized_args: list[Path] = []
    for arg in session.config.args:
        if arg.startswith("-"):
            continue
        candidate = Path(arg)
        normalized_args.append(candidate if candidate.is_absolute() else Path.cwd() / candidate)

    if not normalized_args:
        return False

    lifecycle_root = (Path.cwd() / _LIFECYCLE_TESTS_DIR).resolve()
    for candidate in normalized_args:
        resolved = candidate.resolve()
        try:
            resolved.relative_to(lifecycle_root)
        except ValueError:
            if resolved != lifecycle_root:
                return False
    return True


def _selected_rust_target_name(session: pytest.Session) -> str:
    """Choose the Rust scenario target for the requested test slice."""
    rust_target_name = session.config.getoption("--rust-target-name")
    if rust_target_name != _DEFAULT_RUST_TARGET:
        return rust_target_name
    if _is_lifecycle_only_selection(session):
        return _LIFECYCLE_ONLY_RUST_TARGET
    return rust_target_name


# Cmdline options
def pytest_addoption(parser):
    parser.addoption(
        "--traces",
        choices=["none", "target", "all"],
        default="none",
        help="Verbosity of traces in output and HTML report. "
        '"none" - show no traces, '
        '"target" - show traces generated by test code, '
        '"all" - show all traces. ',
    )

    parser.addoption(
        "--rust-target-name",
        type=str,
        default=_DEFAULT_RUST_TARGET,
        help="Rust test scenario executable target.",
    )
    parser.addoption(
        "--rust-target-path",
        type=Path,
        help="Rust test scenario executable target.",
    )
    parser.addoption(
        "--cpp-target-name",
        type=str,
        default="//feature_integration_tests/test_scenarios/cpp:cpp_test_scenarios",
        help="C++ test scenario executable target.",
    )
    parser.addoption(
        "--cpp-target-path",
        type=Path,
        help="C++ test scenario executable target.",
    )
    parser.addoption(
        "--build-scenarios",
        action="store_true",
        help="Build test scenarios executables.",
    )
    parser.addoption(
        "--build-scenarios-timeout",
        type=float,
        default=180.0,
        help="Build command timeout in seconds. Default: %(default)s",
    )
    parser.addoption(
        "--default-execution-timeout",
        type=float,
        default=5.0,
        help="Default execution timeout in seconds. Default: %(default)s",
    )


# Hooks
def pytest_collection_modifyitems(items: list[pytest.Function]):
    for item in items:
        # Automatically mark tests parametrized with 'version' as 'cpp' or 'rust'.
        # This allows -m cpp / -m rust to select the correct variant in each target.
        if hasattr(item, "callspec") and "version" in getattr(item.callspec, "params", {}):
            version = item.callspec.params["version"]
            if version == "cpp":
                item.add_marker(pytest.mark.cpp)
            elif version == "rust":
                item.add_marker(pytest.mark.rust)


@pytest.hookimpl(tryfirst=True)
def pytest_sessionstart(session):
    try:
        # Build scenarios.
        if session.config.getoption("--build-scenarios"):
            build_timeout = session.config.getoption("--build-scenarios-timeout")
            selected_versions = _selected_versions(session)

            # Build Rust test scenarios.
            if "rust" in selected_versions:
                print("Building Rust test scenarios executable...")
                rust_tools = BazelTools(option_prefix="rust", build_timeout=build_timeout)
                rust_target_name = _selected_rust_target_name(session)
                rust_tools.build(rust_target_name)

            # Build C++ test scenarios.
            if "cpp" in selected_versions:
                print("Building C++ test scenarios executable...")
                cpp_tools = BazelTools(option_prefix="cpp", build_timeout=build_timeout)
                cpp_target_name = session.config.getoption("--cpp-target-name")
                cpp_tools.build(cpp_target_name)

    except Exception as e:
        pytest.exit(str(e), returncode=1)
