# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
import os
import subprocess
from pathlib import Path

import pytest


# Cmdline options
def pytest_addoption(parser):
    parser.addoption(
        "--traces",
        choices=["none", "target", "all"],
        default="none",
        help="Verbosity of traces in output and HTML report. "
        '"none" - show no traces, '
        '"target" - show traces generated by test code, '
        '"all" - show all traces. ',
    )

    parser.addoption(
        "--rust-target-name",
        type=str,
        default="//feature_integration_tests/test_scenarios/rust:rust_test_scenarios",
        help="Rust test scenario executable target.",
    )
    parser.addoption(
        "--rust-target-path",
        type=Path,
        help="Rust test scenario executable target.",
    )
    parser.addoption(
        "--cpp-target-name",
        type=str,
        default="//feature_integration_tests/test_scenarios/cpp:cpp_test_scenarios",
        help="C++ test scenario executable target.",
    )
    parser.addoption(
        "--cpp-target-path",
        type=Path,
        help="C++ test scenario executable target.",
    )
    parser.addoption(
        "--build-scenarios",
        action="store_true",
        help="Build test scenarios executables.",
    )
    parser.addoption(
        "--build-scenarios-timeout",
        type=float,
        default=180.0,
        help="Build command timeout in seconds. Default: %(default)s",
    )
    parser.addoption(
        "--bazel-config",
        type=str,
        default=os.environ.get("FIT_BAZEL_CONFIG", "linux-x86_64"),
        help=('Bazel config used when --build-scenarios is enabled (default: env FIT_BAZEL_CONFIG or "linux-x86_64").'),
    )
    parser.addoption(
        "--default-execution-timeout",
        type=float,
        default=5.0,
        help="Default execution timeout in seconds. Default: %(default)s",
    )


# Hooks
def pytest_configure(config: pytest.Config) -> None:
    """Register custom markers used by FIT parametrization."""
    config.addinivalue_line("markers", "cpp: mark scenario execution for C++ target")
    config.addinivalue_line("markers", "rust: mark scenario execution for Rust target")


def pytest_collection_modifyitems(items: list[pytest.Function]):
    for item in items:
        # Automatically mark tests parametrized with 'version' as 'cpp' or 'rust'.
        # This allows -m cpp / -m rust to select the correct variant in each target.
        if hasattr(item, "callspec") and "version" in getattr(item.callspec, "params", {}):
            version = item.callspec.params["version"]
            if version == "cpp":
                item.add_marker(pytest.mark.cpp)
            elif version == "rust":
                item.add_marker(pytest.mark.rust)


@pytest.hookimpl(tryfirst=True)
def pytest_sessionstart(session):
    try:
        # Build scenarios.
        if session.config.getoption("--build-scenarios"):
            build_timeout = session.config.getoption("--build-scenarios-timeout")
            bazel_config = session.config.getoption("--bazel-config")

            def _build_target(target_name: str) -> None:
                command = ["bazel", "build", f"--config={bazel_config}", target_name]
                result = subprocess.run(
                    command,
                    capture_output=True,
                    text=True,
                    check=False,
                    timeout=build_timeout,
                )
                if result.returncode != 0:
                    stderr_tail = "\n".join(result.stderr.strip().splitlines()[-40:])
                    raise RuntimeError(
                        "Failed to run build with pytest --build-scenarios.\n"
                        f"Command: {' '.join(command)}\n"
                        f"Return code: {result.returncode}\n"
                        f"stderr (last lines):\n{stderr_tail}"
                    )

            # Build Rust test scenarios.
            print(f"Building Rust test scenarios executable with --config={bazel_config}...")
            rust_target_name = session.config.getoption("--rust-target-name")
            _build_target(rust_target_name)

            # Build C++ test scenarios.
            print(f"Building C++ test scenarios executable with --config={bazel_config}...")
            cpp_target_name = session.config.getoption("--cpp-target-name")
            _build_target(cpp_target_name)

    except Exception as e:
        pytest.exit(str(e), returncode=1)
