# *******************************************************************************
# Copyright (c) 2026 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
from pathlib import Path

import pytest
from testing_utils import BazelTools


def _selected_versions(session: pytest.Session) -> set[str]:
    """Return the scenario variants explicitly requested by the mark expression."""
    mark_expression = session.config.option.markexpr or ""
    selected_versions = {version for version in ("rust", "cpp") if version in mark_expression}
    return selected_versions or {"rust", "cpp"}


# Cmdline options
def pytest_addoption(parser):
    parser.addoption(
        "--traces",
        choices=["none", "target", "all"],
        default="none",
        help="Verbosity of traces in output and HTML report. "
        '"none" - show no traces, '
        '"target" - show traces generated by test code, '
        '"all" - show all traces. ',
    )

    parser.addoption(
        "--rust-target-name",
        type=str,
        default="//feature_integration_tests/test_scenarios/rust:rust_test_scenarios",
        help="Rust test scenario executable target.",
    )
    parser.addoption(
        "--rust-target-path",
        type=Path,
        help="Rust test scenario executable target.",
    )
    parser.addoption(
        "--cpp-target-name",
        type=str,
        default="//feature_integration_tests/test_scenarios/cpp:cpp_test_scenarios",
        help="C++ test scenario executable target.",
    )
    parser.addoption(
        "--cpp-target-path",
        type=Path,
        help="C++ test scenario executable target.",
    )
    parser.addoption(
        "--build-scenarios",
        action="store_true",
        help="Build test scenarios executables.",
    )
    parser.addoption(
        "--build-scenarios-timeout",
        type=float,
        default=180.0,
        help="Build command timeout in seconds. Default: %(default)s",
    )
    parser.addoption(
        "--default-execution-timeout",
        type=float,
        default=5.0,
        help="Default execution timeout in seconds. Default: %(default)s",
    )


# Hooks
def pytest_collection_modifyitems(items: list[pytest.Function]):
    for item in items:
        # Automatically mark tests parametrized with 'version' as 'cpp' or 'rust'.
        # This allows -m cpp / -m rust to select the correct variant in each target.
        if hasattr(item, "callspec") and "version" in getattr(item.callspec, "params", {}):
            version = item.callspec.params["version"]
            if version == "cpp":
                item.add_marker(pytest.mark.cpp)
            elif version == "rust":
                item.add_marker(pytest.mark.rust)


@pytest.hookimpl(tryfirst=True)
def pytest_sessionstart(session):
    try:
        # Build scenarios.
        if session.config.getoption("--build-scenarios"):
            build_timeout = session.config.getoption("--build-scenarios-timeout")
            selected_versions = _selected_versions(session)

            # Build Rust test scenarios.
            if "rust" in selected_versions:
                print("Building Rust test scenarios executable...")
                rust_tools = BazelTools(option_prefix="rust", build_timeout=build_timeout)
                rust_target_name = session.config.getoption("--rust-target-name")
                rust_tools.build(rust_target_name)

            # Build C++ test scenarios.
            if "cpp" in selected_versions:
                print("Building C++ test scenarios executable...")
                cpp_tools = BazelTools(option_prefix="cpp", build_timeout=build_timeout)
                cpp_target_name = session.config.getoption("--cpp-target-name")
                cpp_tools.build(cpp_target_name)

    except Exception as e:
        pytest.exit(str(e), returncode=1)
