# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# Workflow configuration for S-CORE CI - Bazel Build & Test baselibs
# This workflow runs Bazel build and test when triggered by specific pull request events.

name: Bazel Build some repositories
on:
  workflow_dispatch:
  push:
    branches: [ bazel ]
jobs:
    integration_test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4.2.2
        - name: Setup Bazel
          uses: bazel-contrib/setup-bazel@0.15.0
          with:
            # Avoid downloading Bazel every time.
            bazelisk-cache: true
            # Store build cache per workflow.
            disk-cache: ${{ github.workflow }}
            # Share repository cache between workflows.
            repository-cache: true
        - name: Bazel build targets
          run: |
            ./integration_test.sh
        - name: Publish build summary
          if: always()
          run: |
            if [ -f _logs/build_summary.md ]; then
              {
                echo '## Bazel Build Summary'
                echo
                sed 's/^/    /' _logs/build_summary.md
              } >> "$GITHUB_STEP_SUMMARY"
            else
              echo "No build summary file found (_logs/build_summary.md)" >> "$GITHUB_STEP_SUMMARY"
            fi
        - name: Upload logs artifact
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: bazel-build-logs
            path: _logs/
            if-no-files-found: warn
            retention-days: 14
