# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

# Workflow configuration for S-CORE CI - Bazel Build & Test baselibs
# This workflow runs Bazel build and test when triggered by specific pull request events.

name: Bazel Build some repositories
on:
  workflow_dispatch:
  push:
    branches: [ bazel ]
  pull_request:
    branches: [ bazel ]
jobs:
    integration_test:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        actions: read
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4.2.2
        - name: Setup Bazel
          uses: bazel-contrib/setup-bazel@0.9.1
        - name: Bazel build baselibs targets
          run: |
            ./integration_test.sh